[package]
name = "quack"
version = "0.1.0"
authors = ["Will Fuqua <wafuqua@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "*"
config = "0.8.0"
failure = "0.1.1"
slack = "0.19.0"
slack_api = "0.18.0"

[build-dependencies]
cc = "1.0"
