/* generated by rust_qt_binding_generator */
#ifndef BINDINGS_H
#define BINDINGS_H

#include <QObject>
#include <QAbstractItemModel>

class Application;
class Channels;

class Application : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Channels* const m_channels;
    Private * m_d;
    bool m_ownsPrivate;
    Q_PROPERTY(Channels* channels READ channels NOTIFY channelsChanged FINAL)
    explicit Application(bool owned, QObject *parent);
public:
    explicit Application(QObject *parent = nullptr);
    ~Application();
    const Channels* channels() const;
    Channels* channels();
signals:
    void channelsChanged();
};

class Channels : public QAbstractItemModel
{
    Q_OBJECT
    friend class Application;
public:
    class Private;
private:
    Private * m_d;
    bool m_ownsPrivate;
    explicit Channels(bool owned, QObject *parent);
public:
    explicit Channels(QObject *parent = nullptr);
    ~Channels();

    int columnCount(const QModelIndex &parent = QModelIndex()) const override;
    QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const override;
    QModelIndex index(int row, int column, const QModelIndex &parent = QModelIndex()) const override;
    QModelIndex parent(const QModelIndex &index) const override;
    bool hasChildren(const QModelIndex &parent = QModelIndex()) const override;
    int rowCount(const QModelIndex &parent = QModelIndex()) const override;
    bool canFetchMore(const QModelIndex &parent) const override;
    void fetchMore(const QModelIndex &parent) override;
    Qt::ItemFlags flags(const QModelIndex &index) const override;
    void sort(int column, Qt::SortOrder order = Qt::AscendingOrder) override;
    int role(const char* name) const;
    QHash<int, QByteArray> roleNames() const override;
    QVariant headerData(int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override;
    bool setHeaderData(int section, Qt::Orientation orientation, const QVariant &value, int role = Qt::EditRole) override;
    Q_INVOKABLE bool insertRows(int row, int count, const QModelIndex &parent = QModelIndex()) override;
    Q_INVOKABLE bool removeRows(int row, int count, const QModelIndex &parent = QModelIndex()) override;
    Q_INVOKABLE QString name(int row) const;

signals:
    // new data is ready to be made available to the model with fetchMore()
    void newDataReady(const QModelIndex &parent) const;
private:
    QHash<QPair<int,Qt::ItemDataRole>, QVariant> m_headerData;
    void initHeaderData();
signals:
};
#endif // BINDINGS_H
